### ISSUE TITLE
Support for string valued signals

### ISSUE THREAD

**Issue by samitbasu** [ekiwi/wellen#15] opened 2024-05-15 20:59 UTC
[test_enum.zip](https://github.com/ekiwi/wellen/files/15326952/test_enum.zip)
Hello,

This is a really great library!  Thanks for the work you have already put into it.  I wonder if you are at all willing to support "string" values in VCD files.  This allows VCD files to use strings (like state names) instead of values in the waveform viewer.  The attached VCD causes a panic when attempting to load it using the example.  It loads and renders fine in GTKWave.  Also the `vcd` crate writes and reads string valued signals as described [here](https://docs.rs/vcd/latest/vcd/struct.Writer.html#method.change_string).

**Comment by ekiwi** [comment] 2024-05-15 21:27
Thanks for filing this issue! If a file can be loaded with GTKWave, we aim to support it.

>  I wonder if you are at all willing to support "string" values in VCD files

These are already supported for some case, I assume that there is a missing feature or a bug in our implementation though.

I will have a look at your test case over the next week or two. Thanks!

**Comment by ekiwi** [comment] 2024-05-15 21:29
@samitbasu Could you please confirm that we are allowed to include your VCD file in our test suite? Also, could you tell me which tool you used to generated the VCD? Our test suite (the `inputs` folder) is organized by tools.

**Comment by ekiwi** [comment] 2024-05-15 21:42
I did some debugging. The problem is that the signal in question is declared to be a 0-bit wire and then gets a string value. Supporting this would be possible, but not quite trivial to do for our multi-threaded VCD parser.

If you control the tool that generated the VCD, then using `string` instead of `wire` should make things work.

**Comment by samitbasu** [comment] 2024-05-22 14:44
Sorry - got caught up in other stuff.
1. You may include that VCD in your test cases if you choose.  
2. The code that produced it is mine (RustHDL).  I will try and fix it.
3. The Rust crate that generated it was `vcd`.
4. I have seen this same pattern (declaring a signal as zero-width and then assigning string values) generated by other tools.    It may be incorrect, but I don't believe it's uncommon.

**Comment by ekiwi** [comment] 2024-05-22 15:08
> Sorry - got caught up in other stuff.

No worries.

After thinking about this a little longer, this is what I have come to: I will leave the issue open, but I won't work on a fix for now. The biggest problem is that `wellen` has a split API for waveform viewers which allows them to have `wellen` only parse the VCD header and then allow the user to start interacting with the scope and variable tree while `wellen` parses the actual value change data in the background. So modifying the Hierarchy meta-data based on what we observe when parsing the body is going to be a challenge. I still think it might be worthwhile to try and come up with a fix, especially if we can find other tools that have a similar problem.

The one other tool for which I have encountered a similar issue is `MyHDL`. In [this example VCD](https://github.com/ekiwi/wellen/blob/main/inputs/my-hdl/sigmoid_tb.vcd) there is a signal declared to be a 1-bit `real`: `$var real 1 , state $end` which is then assigned to string values later on: `scount ,`. Besides that I have not encountered issues with any other tools.

**Comment by samitbasu** [comment] 2024-05-22 15:11
Agree - MyHDL does this.  I'll fix it in my stuff. I will also raise an issue with the MyHDL folks in case they want to fix it.

**Comment by ekiwi** [comment] 2024-05-22 15:12
> The code that produced it is mine (RustHDL). I will try and fix it.

I had a look at the `vcd` crate and it seems like you might want to consider using `add_var` instead of `add_wire`: https://github.com/kevinmehall/rust-vcd/blob/2e451f83661a72216a3c07e4e171731a62f89055/src/write.rs#L179

**Closed** 2024-06-18 18:15 UTC
